version: '3.3'
services:

  db:
    build:
      context: ./docker/db/
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "<YourStrong@Passw0rd>"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: sqlcmd -S db1.internal.prod.example.com -U SA -P '<YourStrong@Passw0rd>' -Q 'select distinct 1 from AdventureWorksDW2017.dbo.DimDate'
    networks:
      mynetwork:
        aliases:
          - db1.internal.prod.example.com
    volumes:
     - mssql-data:/var/opt/mssql

  web:
    build:
      context: ./docker/web/
      dockerfile: Dockerfile
    user: root
    depends_on:
      - db
    volumes:
      - .:/code/
    ports:
      - "8080:8080"
    environment:
      DJANGO_SETTINGS_MODULE: SqlServerOnDocker.settings
    command: python3 manage.py runserver 0.0.0.0:8080
    restart: unless-stopped
    networks:
      mynetwork:
        aliases:
          - web1.internal.prod.example.com

networks:
  mynetwork:
    driver: bridge

volumes:
  mssql-data:
    # actually this is the default
    driver: local